import {
  CREATE_HEARTBEAT_ROUTE,
  DELETE_HEARTBEAT_ROUTE,
  GET_HEARTBEAT_ROUTE,
  LIST_HEARTBEATS_ROUTE,
  PAUSE_HEARTBEAT_ROUTE,
  RESUME_HEARTBEAT_ROUTE,
  RUN_HEARTBEAT_ROUTE,
  UPDATE_HEARTBEAT_ROUTE,
} from '../../handlers/heartbeats';
import type { ServerRoute } from '.';

export const HEARTBEATS_ROUTES: ServerRoute<any, any, any>[] = [
  LIST_HEARTBEATS_ROUTE,
  GET_HEARTBEAT_ROUTE,
  CREATE_HEARTBEAT_ROUTE,
  UPDATE_HEARTBEAT_ROUTE,
  DELETE_HEARTBEAT_ROUTE,
  PAUSE_HEARTBEAT_ROUTE,
  RESUME_HEARTBEAT_ROUTE,
  RUN_HEARTBEAT_ROUTE,
];
